components:
  packages/opentelemetry-id-generator-aws-xray:
    - NathanielRN
    - willarmiros
  plugins/node/opentelemetry-instrumentation-aws-lambda:
    - NathanielRN
    - willarmiros
  propagators/opentelemetry-propagator-aws-xray:
    - NathanielRN
    - willarmiros
  detectors/node/opentelemetry-resource-detector-aws:
    - NathanielRN
    - willarmiros
  detectors/node/opentelemetry-resource-detector-alibaba-cloud:
    - legendecas
  plugins/node/opentelemetry-instrumentation-nestjs-core:
    - Rauno56
