# Keep all in alphabetical order
components:
  detectors/node/opentelemetry-resource-detector-alibaba-cloud:
    - legendecas
  detectors/node/opentelemetry-resource-detector-aws: []
    # Unmaintained
  detectors/node/opentelemetry-resource-detector-azure:
    - jacksonweber
    - hectorhdzg
  detectors/node/opentelemetry-resource-detector-container:
    - abhee11
  detectors/node/opentelemetry-resource-detector-gcp:
    - aabmass
    - punya
  detectors/node/opentelemetry-resource-detector-github: []
    # Unmaintained
  detectors/node/opentelemetry-resource-detector-instana:
    - kirrg001
  incubator/opentelemetry-sampler-aws-xray: []
    # Unmaintained
  metapackages/auto-configuration-propagators:
    - pichlermarc
  metapackages/auto-instrumentations-node:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  metapackages/auto-instrumentations-web:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/baggage-span-processor:
    - mikegoldsmith
    - jamiedanielson
  packages/opentelemetry-host-metrics:
    - legendecas
  packages/opentelemetry-id-generator-aws-xray: []
    # Unmaintained
  packages/opentelemetry-propagation-utils:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/opentelemetry-redis-common: []
    # Unmaintained
  packages/opentelemetry-test-utils:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/winston-transport:
    - hectorhdzg
  plugins/node/instrumentation-amqplib:
    - blumamir
  plugins/node/instrumentation-cucumber:
    - Ugzuzg
  plugins/node/instrumentation-dataloader:
    - henrinormak
  plugins/node/instrumentation-fs: []
    # Unmaintained
  plugins/node/instrumentation-kafkajs:
    - seemk
  plugins/node/instrumentation-lru-memoizer:
    - blumamir
  plugins/node/instrumentation-mongoose:
    - blumamir
  plugins/node/instrumentation-socket.io:
    - mottibec
  plugins/node/instrumentation-tedious: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-aws-lambda: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-aws-sdk:
    - blumamir
  plugins/node/opentelemetry-instrumentation-bunyan:
    - seemk
    - trentm
  plugins/node/opentelemetry-instrumentation-cassandra:
    - seemk
  plugins/node/opentelemetry-instrumentation-connect: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-dns: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-express:
    - JamieDanielson
    - pkanal
  plugins/node/opentelemetry-instrumentation-fastify: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-generic-pool: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-graphql:
    - obecny
  plugins/node/opentelemetry-instrumentation-hapi: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-ioredis:
    - blumamir
    - naseemkullah
  plugins/node/opentelemetry-instrumentation-knex: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-koa: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-memcached: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-mongodb: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-mysql: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-mysql2: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-nestjs-core: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-net:
    - seemk
  plugins/node/instrumentation-runtime-node:
    - d4nyll
  plugins/node/opentelemetry-instrumentation-pg:
    - maryliag
  plugins/node/opentelemetry-instrumentation-pino:
    - seemk
  plugins/node/opentelemetry-instrumentation-redis-4:
    - blumamir
  plugins/node/opentelemetry-instrumentation-redis:
    - blumamir
  plugins/node/opentelemetry-instrumentation-restify: []
    # Unmaintained
  plugins/node/opentelemetry-instrumentation-router: []
    # Unmaintained
  plugins/node/instrumentation-undici:
    - david-luna
    - trentm
  plugins/node/opentelemetry-instrumentation-winston:
    - seemk
  plugins/web/opentelemetry-instrumentation-document-load:
    - pkanal
    - martinkuba
  plugins/web/opentelemetry-instrumentation-long-task:
    - mhennoch
    - t2t2
  plugins/web/opentelemetry-instrumentation-user-interaction:
    - obecny
  plugins/web/opentelemetry-plugin-react-load:
    - martinkuba
  propagators/opentelemetry-propagator-instana:
    - kirrg001
  propagators/opentelemetry-propagator-ot-trace: []
    # Unmaintained
  propagators/propagator-aws-xray: [ ]
  # Unmaintained
  propagators/propagator-aws-xray-lambda: [ ]
  # Unmaintained

ignored-authors:
  - renovate-bot
