# Keep all in alphabetical order
components:
  detectors/node/resource-detector-alibaba-cloud:
    - legendecas
  detectors/node/resource-detector-aws:
    - carolabadeer
  detectors/node/resource-detector-azure:
    - jacksonweber
    - hectorhdzg
  detectors/node/resource-detector-container:
    - abhee11
  detectors/node/resource-detector-gcp:
    - aabmass
    - punya
  detectors/node/resource-detector-github: []
    # Unmaintained?
  detectors/node/resource-detector-instana:
    - basti1302
    - kirrg001
  metapackages/auto-instrumentations-node:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  metapackages/auto-instrumentations-web:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/baggage-span-processor:
    - mikegoldsmith
    - jamiedanielson
  packages/host-metrics:
    - legendecas
  packages/id-generator-aws-xray:
    - carolabadeer
  packages/opentelemetry-sampler-aws-xray:
    - carolabadeer
  packages/propagation-utils:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/redis-common:
    - haddasbronfman
  packages/contrib-test-utils:
    - dyladan
    - pichlermarc
    - legendecas
    - blumamir
  packages/winston-transport:
    - hectorhdzg
  plugins/node/instrumentation-amqplib:
    - blumamir
  plugins/node/instrumentation-cucumber:
    - Ugzuzg
  plugins/node/instrumentation-dataloader:
    - henrinormak
  plugins/node/instrumentation-fs:
    - rauno56
  plugins/node/instrumentation-lru-memoizer:
    - blumamir
  plugins/node/instrumentation-mongoose:
    - blumamir
  plugins/node/instrumentation-socket.io:
    - mottibec
    - rauno56
  plugins/node/instrumentation-tedious:
    - rauno56
  plugins/node/instrumentation-aws-lambda:
    - carolabadeer
  plugins/node/instrumentation-aws-sdk:
    - carolabadeer
    - blumamir
  plugins/node/instrumentation-bunyan:
    - seemk
    - trentm
  plugins/node/instrumentation-cassandra-driver:
    - seemk
  plugins/node/instrumentation-connect: []
    # Unmaintained?
  plugins/node/instrumentation-dns: []
    # Unmaintained?
  plugins/node/instrumentation-express:
    - JamieDanielson
    - pkanal
  plugins/node/instrumentation-fastify:
    - pichlermarc
  plugins/node/instrumentation-generic-pool:
    - rauno56
  plugins/node/instrumentation-graphql:
    - obecny
  plugins/node/instrumentation-hapi: []
    # Unmaintained?
  plugins/node/instrumentation-ioredis:
    - blumamir
    - naseemkullah
  plugins/node/instrumentation-knex:
    - rauno56
  plugins/node/instrumentation-koa: []
    # Unmaintained?
  plugins/node/instrumentation-memcached:
    - rauno56
  plugins/node/instrumentation-mongodb:
    - osherv
  plugins/node/instrumentation-mysql:
    - haddasbronfman
  plugins/node/instrumentation-mysql2:
    - haddasbronfman
  plugins/node/instrumentation-nestjs-core:
    - rauno56
  plugins/node/instrumentation-net:
    - seemk
  plugins/node/opentelemetry-instrumentation-runtime-node:
    - d4nyll
  plugins/node/instrumentation-pg:
    - maryliag
    - rauno56
  plugins/node/instrumentation-pino:
    - seemk
  plugins/node/instrumentation-redis-4:
    - blumamir
  plugins/node/instrumentation-redis:
    - blumamir
  plugins/node/instrumentation-restify:
    - rauno56
  plugins/node/instrumentation-router:
    - rauno56
  plugins/node/opentelemetry-instrumentation-undici:
    - david-luna
    - trentm
  plugins/node/instrumentation-winston:
    - seemk
  plugins/web/instrumentation-document-load:
    - pkanal
    - martinkuba
  plugins/web/instrumentation-long-task:
    - mhennoch
    - t2t2
  plugins/web/instrumentation-user-interaction:
    - obecny
  plugins/web/plugin-react-load:
    - martinkuba
  propagators/opentelemetry-propagator-grpc-census-binary: []
    # Unmaintained?
  propagators/propagator-instana:
    - basti1302
    - kirrg001
  propagators/propagator-ot-trace: []
    # Unmaintained?

ignored-authors:
  - renovate-bot
