# Keep all in alphabetical order
components:
  detectors/node/opentelemetry-resource-detector-alibaba-cloud:
    - legendecas
  detectors/node/opentelemetry-resource-detector-aws:
    - NathanielRN
    - willarmiros
  metapackages/auto-instrumentations-node:
    - obecny
  metapackages/auto-instrumentations-web:
    - obecny
  packages/opentelemetry-host-metrics:
    - obecny
  packages/opentelemetry-id-generator-aws-xray:
    - NathanielRN
    - willarmiros
  plugins/node/opentelemetry-instrumentation-aws-lambda:
    - NathanielRN
    - willarmiros
  plugins/node/opentelemetry-instrumentation-aws-sdk:
    - NathanielRN
    - willarmiros
    - blumamir
  plugins/node/opentelemetry-instrumentation-generic-pool:
    - rauno56
  plugins/node/opentelemetry-instrumentation-graphql:
    - obecny
  plugins/node/opentelemetry-instrumentation-ioredis:
    - blumamir
    - naseemkullah
  plugins/node/opentelemetry-instrumentation-knex:
    - rauno56
  plugins/node/opentelemetry-instrumentation-memcached:
    - rauno56
  plugins/node/opentelemetry-instrumentation-nestjs-core:
    - rauno56
  plugins/node/opentelemetry-instrumentation-redis:
    - blumamir
  plugins/node/opentelemetry-instrumentation-restify:
    - rauno56
  plugins/node/opentelemetry-instrumentation-router:
    - rauno56
  plugins/node/opentelemetry-instrumentation-pg:
    - rauno56
  plugins/web/opentelemetry-instrumentation-document-load:
    - obecny
  plugins/web/opentelemetry-instrumentation-long-task:
    - mhennoch
    - t2t2
  plugins/web/opentelemetry-instrumentation-user-interaction:
    - obecny
  propagators/opentelemetry-propagator-aws-xray:
    - NathanielRN
    - willarmiros

ignored-authors:
  - renovate-bot
