"@koa/router":
  jobs:
    - versions:
        include: ">=8.0.0 <13"
        mode: latest-minors
      commands: npm run test
    - versions:
        include: ">=13 <14"
        mode: latest-minors
      node: '>=18'
      commands: npm run test

koa:
  # Testing ^2.7.0 covers at least 97% of the downloaded koa versions
  versions:
    include: "^3.0.1"
    mode: latest-minors
  commands: npm run test
