pino:
  - versions:
      include: '>=9.0.0 <10'
      mode: latest-minors
    node: ">=18"
    commands: npm run test
  - versions:
      include: '>=5.14.0 <9'
      mode: max-7
    node: ">=14"
    commands: npm run test
