/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview Type definitions for GenAI telemetry.
 * All types and interfaces defined in this package are currently experimental.
 *
 * @experimental
 */

import type { Attributes, Context, TimeInput } from '@opentelemetry/api';

/**
 * Mode of capturing message content (prompts, completions, tool calls).
 *
 * NOTE: OpenTelemetry Semantic Conventions define GenAI events (such as
 * `gen_ai.client.inference.operation.details`) as Log-based Events (LogRecords
 * with an event name). Because the Logs API in OpenTelemetry JavaScript is not yet
 * stable, event-based capture modes (`event_only`, `span_and_event`) are not yet
 * supported in this library. Content capture is currently limited to `span_only`
 * (recording on span attributes) and `none`.
 */
export type ContentCaptureMode = 'none' | 'span_only';

/**
 * Reason why the model finished generating output.
 *
 * Corresponds to `gen_ai.response.finish_reasons`.
 */
export type FinishReason =
  | 'stop'
  | 'length'
  | 'content_filter'
  | 'tool_call'
  | 'compaction'
  | 'error'
  | (string & {});

/**
 * Role of the message sender in a chat conversation.
 */
export type Role = 'system' | 'user' | 'assistant' | 'tool' | string;

/**
 * Modality of multimodal content (e.g. image, video, audio, document).
 */
export type Modality = 'image' | 'video' | 'audio' | 'document' | string;

/**
 * The modality of the tokens being counted (`gen_ai.token.modality`).
 *
 * A custom value MAY be used when none of the well-known values applies.
 */
export type TokenModality = 'audio' | 'image' | 'text' | 'unknown';

/**
 * Token counts keyed by modality, e.g. `{ text: 100, image: 200 }`.
 */
export type TokenCountsByModality = Partial<Record<TokenModality, number>>;

/**
 * Classification of tool utilized by an agent.
 *
 * Corresponds to `gen_ai.tool.type`.
 */
export type ToolType = 'function' | 'extension' | 'datastore' | string;

/**
 * Lifecycle status of a generated response, as reported by the provider.
 *
 * Corresponds to `gen_ai.response.status`.
 */
export type ResponseStatus =
  | 'queued'
  | 'in_progress'
  | 'completed'
  | 'incomplete'
  | 'failed'
  | 'cancelled'
  | string;

// ============================================================================
// Message Parts (per gen-ai-input-messages.json / gen-ai-output-messages.json)
// ============================================================================

/**
 * Generic message part for extensible content.
 */
export interface GenericPart {
  /** The type of content captured in this part. */
  type: string;
  [key: string]: unknown;
}

/**
 * Text content part sent to or received from a model.
 */
export interface TextPart {
  type: 'text';
  /** Text content sent to or received from the model. */
  content: string;
  [key: string]: unknown;
}

/**
 * Binary / multimodal blob part (e.g. image, audio, video, document).
 */
export interface BlobPart {
  type: 'blob';
  /** Modality of the content (e.g. image, audio, video, document). */
  modality: Modality;
  /** Raw bytes of the attached data. */
  content: Uint8Array;
  /** The IANA MIME type of the attached data. */
  mime_type?: string | null;
  [key: string]: unknown;
}

/**
 * Tool call requested by the model.
 */
export interface ToolCallRequestPart {
  type: 'tool_call';
  /** Unique tool call identifier. */
  id?: string | null;
  /** Name of the tool to execute. */
  name: string;
  /** Arguments passed to the tool. */
  arguments?: unknown | null;
  [key: string]: unknown;
}

/**
 * Tool execution result sent back to the model.
 */
export interface ToolCallResponsePart {
  type: 'tool_call_response';
  /** Matching tool call identifier. */
  id?: string | null;
  /** Tool call response / output. */
  response: unknown;
  [key: string]: unknown;
}

/**
 * Reasoning / thinking content generated by reasoning models (e.g. o1/o3, DeepSeek R1).
 */
export interface ReasoningPart {
  type: 'reasoning';
  /** Reasoning / thought content received from the model. */
  content: string;
  [key: string]: unknown;
}

/**
 * Context window compaction summary or event.
 */
export interface CompactionPart {
  type: 'compaction';
  /** Provider-assigned identifier for the compaction item or block. */
  id?: string | null;
  /** The unencrypted compacted conversation summary, when available. */
  content?: string | null;
  [key: string]: unknown;
}

/**
 * Uploaded file referenced by identifier.
 */
export interface FilePart {
  type: 'file';
  /** Unique identifier referencing a file that was pre-uploaded to the provider. */
  file_id: string;
  /** Modality of the content (e.g. image, audio, video, document). */
  modality: Modality;
  /** The IANA MIME type of the attached data. */
  mime_type?: string | null;
  [key: string]: unknown;
}

/**
 * File or resource referenced by URI.
 */
export interface UriPart {
  type: 'uri';
  /** A URI referencing attached data. */
  uri: string;
  /** Modality of the content (e.g. image, audio, video, document). */
  modality: Modality;
  /** The IANA MIME type of the attached data. */
  mime_type?: string | null;
  [key: string]: unknown;
}

/**
 * Generic server-side tool call details.
 */
export interface GenericServerToolCall {
  /** Type identifier for the server tool call. */
  type: string;
  [key: string]: unknown;
}

/**
 * Generic server-side tool call response details.
 */
export type GenericServerToolCallResponse = GenericServerToolCall;

/**
 * Server-side tool call requested by the provider (e.g. built-in web search, code interpreter).
 */
export interface ServerToolCallPart {
  type: 'server_tool_call';
  /** Name of the server tool. */
  name: string;
  /** Polymorphic server tool call details with type discriminator. */
  server_tool_call: GenericServerToolCall;
  /** Unique identifier for the server tool call. */
  id?: string | null;
  [key: string]: unknown;
}

/**
 * Result of a server-side tool call.
 */
export interface ServerToolCallResponsePart {
  type: 'server_tool_call_response';
  /** Polymorphic server tool call response with type discriminator. */
  server_tool_call_response: GenericServerToolCallResponse;
  /** Unique server tool call identifier matching the original call. */
  id?: string | null;
  [key: string]: unknown;
}

/**
 * Union of all supported message parts.
 */
export type MessagePart =
  | TextPart
  | BlobPart
  | ToolCallRequestPart
  | ToolCallResponsePart
  | ServerToolCallPart
  | ServerToolCallResponsePart
  | ReasoningPart
  | CompactionPart
  | FilePart
  | UriPart
  | GenericPart;

/**
 * System instruction part for use in SystemInstructions.
 */
export type SystemInstructionPart = TextPart | GenericPart;

// ============================================================================
// Messages and Conversations
// ============================================================================

/**
 * Chat message representing an input or output in a conversation.
 */
export interface ChatMessage {
  /** Role of the entity that created the message. */
  role: Role;
  /** List of message parts comprising the content. */
  parts: MessagePart[];
  /** The name of the participant. */
  name?: string | null;
  [key: string]: unknown;
}

/**
 * List of input messages sent to the model.
 */
export type InputMessages = ChatMessage[];

/**
 * Output message generated by the model for a specific choice / candidate.
 */
export interface OutputMessage {
  /** Role of the entity that created the message (typically 'assistant'). */
  role: Role;
  /** List of message parts comprising the completion. */
  parts: MessagePart[];
  /** The name of the participant. */
  name?: string | null;
  [key: string]: unknown;
}

/**
 * List of output messages produced by the model.
 */
export type OutputMessages = OutputMessage[];

/**
 * List of system instruction parts provided to guide the model.
 */
export type SystemInstructions = SystemInstructionPart[];

/**
 * Token usage of a single inference operation, as reported by the provider.
 *
 * The span attributes and the token metrics are all derived from these
 * values, so they stay consistent. Prefer billable counts when the provider
 * reports both used and billable tokens. Leave fields `undefined` when they
 * were not reported; do not default to `0`, which would skew the token
 * distributions.
 */
export interface TokenUsage {
  /** The number of input (prompt) tokens used per inference operation. */
  inputTokens?: TokenCountsByModality;
  /** The number of output (completion) tokens used per inference operation. */
  outputTokens?: TokenCountsByModality;
  /** Number of tokens used for model reasoning / thinking (`gen_ai.client_inference.usage.reasoning.output_tokens`). */
  reasoningTokens?: TokenCountsByModality;
  /** Number of cached tokens read from prompt cache (`gen_ai.client_inference.usage.cache_read.input_tokens`). */
  cacheReadTokens?: TokenCountsByModality;
  /** Number of tokens written to prompt cache (`gen_ai.client_inference.usage.cache_write.input_tokens`). */
  cacheWriteTokens?: TokenCountsByModality;
  /** The number of input (prompt) tokens used per inference operation. */
  inputOperationTokens?: number;
  /** The number of output (completion) tokens used per inference operation. */
  outputOperationTokens?: number;
}

/**
 * Standard parameters for a GenAI inference request.
 *
 * Every attribute produced from this interface is defined by the GenAI
 * semantic conventions on the inference span only; other invocation types
 * (embeddings, execute tool, ...) declare their own request parameters.
 */
export interface InferenceRequestOptions {
  /** Sampling temperature (`gen_ai.request.temperature`). */
  temperature?: number;
  /** Top-p nucleus sampling parameter (`gen_ai.request.top_p`). */
  topP?: number;
  /** Top-k sampling parameter (`gen_ai.request.top_k`). */
  topK?: number;
  /** Maximum number of tokens to generate (`gen_ai.request.max_tokens`). */
  maxTokens?: number;
  /** Stop sequences (`gen_ai.request.stop_sequences`). */
  stopSequences?: string[];
  /** Frequency penalty parameter (`gen_ai.request.frequency_penalty`). */
  frequencyPenalty?: number;
  /** Presence penalty parameter (`gen_ai.request.presence_penalty`). */
  presencePenalty?: number;
  /** Number of choices/completions requested (`gen_ai.request.choice.count`). */
  choiceCount?: number;
  /** Random seed for deterministic generation (`gen_ai.request.seed`). */
  seed?: number;
  /** Whether the request was streamed (`gen_ai.request.stream`). */
  stream?: boolean;
  /** The requested reasoning effort/level (`gen_ai.request.reasoning.level`). */
  reasoningLevel?: string;
}

// ============================================================================
// Invocation Options
// ============================================================================

/**
 * Options shared by all invocation types.
 *
 * This is the caller-facing counterpart of `BaseInvocationOptions`, which is the
 * contract between a concrete invocation and its base class: the span kind is chosen
 * by the concrete invocation, and `parentContext` is passed to the base class as
 * `context`.
 */
interface CommonInvocationOptions {
  /** Parent context for the span. Defaults to the currently active context. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
  /**
   * Custom metric attributes, recorded on this invocation's metrics only. They override
   * the semantic convention dimensions the invocation would otherwise report (except
   * `error.type`) and must be low cardinality.
   */
  metricAttributes?: Attributes;
  /** Start time of the invocation. Defaults to the time the invocation is created. */
  startTime?: TimeInput;
}

/**
 * Options for starting an inference invocation.
 */
export interface InferenceInvocationOptions extends CommonInvocationOptions {
  /** Name of the provider (e.g. 'openai', 'anthropic', 'aws.bedrock'). */
  providerName: string;
  /** Operation name (e.g. 'chat', 'text_completion', 'generate_content'). Defaults to 'chat'. */
  operationName?: string;
  /** Model name requested. */
  requestModel?: string;
  /** Request parameters/settings. */
  requestOptions?: InferenceRequestOptions;
  /** Input messages sent to the model. */
  inputMessages?: InputMessages;
  /** System instructions. */
  systemInstructions?: SystemInstructions;
  /** Conversation / session / thread ID. */
  conversationId?: string;
  /** Server address (e.g. hostname). */
  serverAddress?: string;
  /** Server port. */
  serverPort?: number;
}

/**
 * Options for starting an embedding invocation.
 */
export interface EmbeddingInvocationOptions extends CommonInvocationOptions {
  /** Name of the provider. */
  providerName: string;
  /** Operation name (e.g. 'embedding', 'generate_content'). Defaults to 'embeddings'. */
  operationName?: string;
  /** Model name requested. */
  requestModel?: string;
  /** Target encoding formats requested (`gen_ai.request.encoding_formats`). */
  encodingFormats?: string[];
  /** Number of dimensions the resulting output embeddings should have (`gen_ai.embeddings.dimension.count`). */
  dimensionCount?: number;
  /** Server address. */
  serverAddress?: string;
  /** Server port. */
  serverPort?: number;
}

/**
 * Options for starting a tool execution invocation.
 */
export interface ToolInvocationOptions extends CommonInvocationOptions {
  /** Name of the tool being executed (`gen_ai.tool.name`). */
  toolName: string;
  /**
   * Operation name (`gen_ai.operation.name`). Defaults to `'execute_tool'`.
   */
  operationName?: string;
  /** Description of the tool (`gen_ai.tool.description`). */
  toolDescription?: string;
  /** Unique ID of the tool call (`gen_ai.tool.call.id`). */
  toolCallId?: string;
  /** Type classification of the tool (`gen_ai.tool.type`). */
  toolType?: ToolType;
  /** Arguments provided to the tool (`gen_ai.tool.call.arguments`). */
  toolArguments?: unknown;
  /** Conversation / session / thread ID (`gen_ai.conversation.id`). */
  conversationId?: string;
  /** Human-readable name of the agent executing the tool (`gen_ai.agent.name`). */
  agentName?: string;
}

/**
 * Base configuration interface for GenAI instrumentations.
 */
export interface GenAIInstrumentationConfig {
  /**
   * Controls capturing of prompt, completion, and tool call contents.
   * - `'none'`: no content captured (default).
   * - `'span_only'`: content captured on span attributes.
   */
  captureMessageContent?: ContentCaptureMode;
}

/**
 * Error details for an invocation that failed.
 *
 * @experimental This type is experimental and subject to change.
 */
export interface InvocationError {
  /**
   * The underlying exception that caused the invocation to fail, if available.
   *
   * When {@link errorType} is not explicitly provided, the error type is automatically
   * derived from this exception (e.g. from its `name` or `code`).
   */
  exception?: Error;

  /**
   * Describes a class of error the operation ended with (`error.type`). SHOULD be predictable and
   * SHOULD have low cardinality.
   *
   * If omitted, defaults to the error type derived from {@link exception}, or `'_OTHER'`.
   */
  errorType?: string;

  /**
   * Human readable additional information about the error which is not expected to contain
   * sensitive details.
   *
   * SHOULD be documented and predictable. Instrumentation libraries SHOULD publish their own
   * conventions, including possible values of description and what they mean.
   *
   * When provided, this is set as the span status description (`Span.setStatus({ code: ERROR, message: statusDescription })`).
   * If omitted, the span status description is left unset to prevent leaking sensitive or high-cardinality error messages.
   */
  statusDescription?: string;
}
