/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Attributes, Span, Context } from '@opentelemetry/api';

/**
 * Mode of capturing message content (prompts, completions, tool calls).
 */
export type ContentCaptureMode =
  | 'none'
  | 'span_only'
  | 'event_only'
  | 'span_and_event';

/**
 * Reason why the model finished generating output.
 */
export type FinishReason =
  | 'stop'
  | 'length'
  | 'content_filter'
  | 'tool_call'
  | 'error'
  | string;

/**
 * Role of the message sender in a chat conversation.
 */
export type Role = 'system' | 'user' | 'assistant' | 'tool' | string;

/**
 * Generic message part for extensible content.
 */
export interface GenericPart {
  /** The type of content captured in this part. */
  type: string;
  [key: string]: unknown;
}

/**
 * Text content part sent to or received from a model.
 */
export interface TextPart extends GenericPart {
  type: 'text';
  /** Text content. */
  content: string;
}

/**
 * Binary / multimodal blob part (e.g. image, audio, video, document).
 */
export interface BlobPart extends GenericPart {
  type: 'blob';
  /** Modality of the content (e.g. image, audio, video). */
  modality?: string;
  /** MIME type of the content (e.g. image/jpeg, audio/wav). */
  mime_type?: string;
  /** Base64-encoded or URI content. */
  content?: string;
}

/**
 * Tool call requested by the model.
 */
export interface ToolCallRequestPart extends GenericPart {
  type: 'tool_call';
  /** Unique tool call identifier. */
  id?: string | null;
  /** Name of the tool to execute. */
  name: string;
  /** Arguments passed to the tool. */
  arguments?: unknown | null;
}

/**
 * Tool execution result sent back to the model.
 */
export interface ToolCallResponsePart extends GenericPart {
  type: 'tool_call_response';
  /** Matching tool call identifier. */
  id?: string | null;
  /** Tool call response / output. */
  response: unknown;
}

/**
 * Union of all supported message parts.
 */
export type MessagePart =
  | TextPart
  | BlobPart
  | ToolCallRequestPart
  | ToolCallResponsePart
  | GenericPart;

/**
 * Chat message representing an input or output in a conversation.
 */
export interface ChatMessage {
  /** Role of the entity that created the message. */
  role: Role;
  /** List of message parts comprising the content. */
  parts: MessagePart[];
  [key: string]: unknown;
}

/**
 * List of input messages sent to the model.
 */
export type InputMessages = ChatMessage[];

/**
 * Output message generated by the model for a specific choice / candidate.
 */
export interface OutputMessage {
  /** Role of the entity that created the message (typically 'assistant'). */
  role: Role;
  /** List of message parts comprising the completion. */
  parts: MessagePart[];
  /** Reason why generation finished. */
  finish_reason?: FinishReason;
  [key: string]: unknown;
}

/**
 * List of output messages produced by the model.
 */
export type OutputMessages = OutputMessage[];

/**
 * System instructions provided to guide the model.
 */
export type SystemInstruction =
  | string
  | {
      parts: MessagePart[];
    };

/**
 * Token usage counts for a request.
 */
export interface TokenUsage {
  /** Number of tokens in the prompt / input. */
  inputTokens?: number;
  /** Number of tokens in the completion / output. */
  outputTokens?: number;
  /** Total tokens (input + output). */
  totalTokens?: number;
}

/**
 * Standard parameters for a GenAI request.
 */
export interface GenAIRequestOptions {
  /** Sampling temperature. */
  temperature?: number;
  /** Top-p nucleus sampling parameter. */
  topP?: number;
  /** Top-k sampling parameter. */
  topK?: number;
  /** Maximum number of tokens to generate. */
  maxTokens?: number;
  /** Stop sequences. */
  stopSequences?: string[];
  /** Frequency penalty parameter. */
  frequencyPenalty?: number;
  /** Presence penalty parameter. */
  presencePenalty?: number;
  /** Number of choices/completions requested. */
  choiceCount?: number;
  /** Random seed for deterministic generation. */
  seed?: number;
  /** Target encoding formats. */
  encodingFormats?: string[];
}

/**
 * Options for starting an inference invocation.
 */
export interface InferenceInvocationOptions {
  /** Name of the provider (e.g. 'openai', 'anthropic', 'aws.bedrock'). */
  providerName: string;
  /** Operation name (e.g. 'chat', 'text_completion', 'generate_content'). Defaults to 'chat'. */
  operationName?: string;
  /** Model name requested. */
  requestModel?: string;
  /** Request parameters/settings. */
  requestOptions?: GenAIRequestOptions;
  /** Input messages sent to the model. */
  inputMessages?: InputMessages;
  /** System instructions. */
  systemInstructions?: SystemInstruction;
  /** Conversation / session / thread ID. */
  conversationId?: string;
  /** Parent context for the span. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
  /** Server address (e.g. hostname). */
  serverAddress?: string;
  /** Server port. */
  serverPort?: number;
}

/**
 * Options for starting an embedding invocation.
 */
export interface EmbeddingInvocationOptions {
  /** Name of the provider. */
  providerName: string;
  /** Model name requested. */
  requestModel?: string;
  /** Input texts to embed. */
  inputTexts?: string[];
  /** Parent context. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
  /** Server address. */
  serverAddress?: string;
  /** Server port. */
  serverPort?: number;
}

/**
 * Options for starting a tool execution invocation.
 */
export interface ToolInvocationOptions {
  /** Name of the tool being executed. */
  toolName: string;
  /** Description of the tool. */
  toolDescription?: string;
  /** Unique ID of the tool call. */
  toolCallId?: string;
  /** Arguments provided to the tool. */
  toolArguments?: unknown;
  /** Parent context. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
}

/**
 * Options for starting an agent invocation.
 */
export interface AgentInvocationOptions {
  /** Unique ID of the agent. */
  agentId?: string;
  /** Name of the agent. */
  agentName?: string;
  /** Description of the agent. */
  agentDescription?: string;
  /** Parent context. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
}

/**
 * Options for starting a workflow invocation.
 */
export interface WorkflowInvocationOptions {
  /** Name of the workflow. */
  workflowName: string;
  /** Parent context. */
  parentContext?: Context;
  /** Custom initial span attributes. */
  attributes?: Attributes;
}

/**
 * Summary result passed to CompletionHook upon invocation finish.
 */
export interface CompletionResult {
  /** The OpenTelemetry span for this invocation. */
  span: Span;
  /** Provider name. */
  providerName?: string;
  /** Operation name. */
  operationName?: string;
  /** Requested model name. */
  requestModel?: string;
  /** Response model name. */
  responseModel?: string;
  /** Response ID. */
  responseId?: string;
  /** Finish reasons. */
  finishReasons?: string[];
  /** Token usage. */
  usage?: TokenUsage;
  /** Duration of the operation in seconds. */
  durationSeconds?: number;
  /** Input messages if captured. */
  inputMessages?: InputMessages;
  /** Output messages if captured. */
  outputMessages?: OutputMessages;
  /** System instructions if captured. */
  systemInstructions?: SystemInstruction;
  /** Error if the invocation failed. */
  error?: Error | unknown;
  /** Custom attributes. */
  attributes?: Attributes;
}

/**
 * Hook executed when a GenAI operation finishes (success or failure).
 */
export interface CompletionHook {
  /**
   * Callback invoked when a GenAI operation completes.
   * If an exception is thrown, it will be safely caught and logged without affecting user flow.
   */
  onCompletion(result: CompletionResult): void | Promise<void>;
}

/**
 * Base configuration interface for GenAI instrumentations.
 */
export interface GenAIInstrumentationConfig {
  /**
   * Controls capturing of prompt, completion, and tool call contents.
   * - `false` or `'none'`: no content captured (default).
   * - `true` or `'span_only'`: content captured on span attributes.
   * - `'event_only'`: content captured in span events.
   * - `'span_and_event'`: content captured in both spans and events.
   */
  captureMessageContent?: boolean | ContentCaptureMode;

  /**
   * Whether to emit detailed span events for messages and choices.
   */
  emitEvents?: boolean;

  /**
   * Optional custom completion hooks.
   */
  completionHooks?: CompletionHook[];
}
