"fastify":
  - versions:
      include: "^4.0.0"
      mode: max-7
    commands: npm run test
  - versions:
      include: ">=5 <6"
      mode: max-7
    commands: npm run test
    peerDependencies: "@fastify/express@4.0.1"
    node: '>=20'

# Fastify versions after 4.18.0 require a typescript greater than 4.4.4.
"typescript":
  - versions: "4.7.4"
