mongodb:
  - versions:
      include: ">=3.3 <4"
      mode: max-7
    commands: npm run test-v3
  - versions:
      include: ">=4 <5"
      # This version has been excluded because `mongoose` instrumentation has
      # it pinned as a transitive dependency.  When `test-all-versions` tries
      # to install it, **npm actually does nothing** and we end up running
      # tests for the wrong version.
      # Ref: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2001#issuecomment-1992202942
      exclude: "4.17.2"
      mode: max-7
    commands: npm run test-v4
  - versions:
      include: ">=5 <6"
      mode: max-7
    commands: npm run test-v5-v6
  - versions:
      include: ">=6 <7"
      mode: max-7
    node: '>=15.0.0'
    commands: npm run test-v5-v6
