mongoose:
  - versions:
      include: ">=5.9.7 <7"
      mode: latest-minors
    commands: npm run test-v5-v6
  - versions:
      include: ">=7 <8"
      mode: latest-minors
    node: '>=14.20.1'
    commands: npm run test-v7-v8
  - versions:
      include: ">=8 <9"
      mode: latest-minors
    node: '>=16.20.1'
    commands: npm run test-v7-v8
