knex:
  jobs:
    - versions:
        include: ">=1.0.0 <2"
        mode: max-3
      peerDependencies: "@vscode/sqlite3@^5.0.7"
      commands: npm run test
    - versions:
        include: ">=2.0.0 <4"
        exclude: '3.0.0' # broken release
        mode: max-3
      commands: npm run test
