name: Test All Versions
on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:
    inputs:
      npm-workspace-args:
        type: string
  workflow_call:
    inputs:
      npm-workspace-args:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-and-cache:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      # Use the same Node.js version used for `release-please` workflow.
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 18
      - name: Install
        run: npm ci --ignore-scripts
        timeout-minutes: 10
      - name: Build
        run: npm run compile
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tav-build-cache-${{ github.run_number }}
          path: .nx
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  tav:
    name: Run test-all-versions
    needs: build-and-cache
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20", "22", "24"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        # Post install scripts are required for some deps for successful test
        # runs: sqlite3, better-sqlite3, and possibly esbuild.
        run: npm ci
        timeout-minutes: 10
      - name: Download Build Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tav-build-cache-${{ github.run_number }}
          path: .nx
      - name: Build
        run: npm run compile
      - name: Start Test Services
        run: npm run test-services:start
      - name: Run test-all-versions
        run: npm run --if-present --workspaces test-all-versions ${INPUTS_NPM_WORKSPACE_ARGS}
        env:
          INPUTS_NPM_WORKSPACE_ARGS: ${{ inputs.npm-workspace-args }}
      - name: Stop Test Services
        if: always()
        run: npm run test-services:stop
      
