name: Create OTel deps update PR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-or-update-deps-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_JS_CONTRIB_APP_ID }}
          private-key: ${{ secrets.OTELBOT_JS_CONTRIB_PRIVATE_KEY }}
          # Scope to just the permissions required by "Create PR" step below.
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          token: ${{ steps.otelbot-token.outputs.token }}
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version: 24

      - run: npm install -g npm@latest

      - run: npm ci --ignore-scripts

      - name: Create PR
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com
          git checkout -b otelbot/update-otel-deps
          node ./scripts/update-otel-deps.js
          git commit -am "feat(deps): update deps matching '@opentelemetry/*'"
          git push --set-upstream origin otelbot/update-otel-deps --force
          gh pr create --title "feat(deps): update deps matching '@opentelemetry/*'" --body 'Updates all `@opentelemetry/*` dependencies to latest'
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
